spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/os_base_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    loadbalancer:
      retry:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
    feign:
      enabled: true

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  logback:
    rollingpolicy:
      max-file-size: 1GB
  file:
    path: logs/

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
      table-prefix: oauth2_
