spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/os_base_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20

  sleuth:
    sampler:
      probability: 1.0
    feign:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    loadbalancer:
      retry:
        enabled: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  logback:
    rollingpolicy:
      max-file-size: 1GB
  file:
    path: logs/

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
